Repository TijClass/VikingsTeam, pull requests merged in 2021-03, with the labels that each got.

#13 add font and helpers
  .gitignore
  src/helpers/functions.php
  src/index.php
  tailwind.config.js
Labels: enhancement

#14 feat(components): add section gallery
  package-lock.json
  src/components/gallery.php
  src/styles/main.css
Labels: enhancement

#15 add footer section
  src/components/footer.php
Labels: Task 🔨, enhancement

#17 style(components): change background color in gallery section.
  src/components/gallery.php
Labels: duplicate

#22 merge b3ns44d to master
  package.json
  src/app/newsletter.php
  src/assets/js/script.js
  src/components/footer.php
  src/components/story.php
  src/contexts/init.php
  src/helpers/functions.php
  src/index.php
  src/sql/bookingSchema.sql
  src/sql/newsletterdb.sql
  src/sql/postdb.sql
  src/sql/userdb.sql
  tailwind.config.js
Labels: enhancement, good first issue
